# Generated by Django 5.2.6 on 2025-09-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField()),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
